package com.game.mario.util;

public enum MarioState {
    STANDING,
    WALKING,
    JUMPING,
    FALLING,
    DEAD,
    WIN,
    ON_OBJECT,
    BLOCKING_BY_OBJECT_HORIZONTAL,
    BLOCKING_BY_OBJECT_VERTICAL,
    BLOCKING_BY_SKY,
    BLOCKING_BY_HORIZONTAL_BEGINNING_MAP,
    BLOCKING_BY_HORIZONTAL_END_MAP,
    HIT_COIN,
    KILLING_ANTAGONIST,
    ZOMBIFIYING_ANTAGONIST,
    HIT_BY_ANTAGONIST,
}
