# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\x12\x05proto\" \n\x08Position\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"+\n\nDimensions\x12\x0e\n\x06height\x18\x01 \x01(\x05\x12\r\n\x05width\x18\x02 \x01(\x05\"\xbd\x01\n\x05Mario\x12!\n\x08position\x18\x01 \x01(\x0b\x32\x0f.proto.Position\x12%\n\ndimensions\x18\x02 \x01(\x0b\x32\x11.proto.Dimensions\x12\x14\n\x0cnumberOfLive\x18\x03 \x01(\x05\x12&\n\x05state\x18\x04 \x03(\x0b\x32\x17.proto.Mario.StateEntry\x1a,\n\nStateEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x08:\x02\x38\x01\"\x95\x01\n\nAntagonist\x12!\n\x08position\x18\x01 \x01(\x0b\x32\x0f.proto.Position\x12%\n\ndimensions\x18\x02 \x01(\x0b\x32\x11.proto.Dimensions\x12\r\n\x05speed\x18\x03 \x01(\x05\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x0e\n\x06isdead\x18\x05 \x01(\x08\x12\x10\n\x08isZombie\x18\x06 \x01(\x08\"^\n\x04Item\x12!\n\x08position\x18\x01 \x01(\x0b\x32\x0f.proto.Position\x12%\n\ndimensions\x18\x02 \x01(\x0b\x32\x11.proto.Dimensions\x12\x0c\n\x04name\x18\x03 \x01(\t\"P\n\x04\x43oin\x12!\n\x08position\x18\x01 \x01(\x0b\x32\x0f.proto.Position\x12%\n\ndimensions\x18\x02 \x01(\x0b\x32\x11.proto.Dimensions\"\xda\x01\n\x08GameData\x12\x1b\n\x05mario\x18\x01 \x01(\x0b\x32\x0c.proto.Mario\x12\x13\n\x0b\x66loor_level\x18\x02 \x01(\x05\x12 \n\x18\x61ntagonist_context_width\x18\x03 \x01(\x05\x12\x1a\n\x12item_context_width\x18\x04 \x01(\x05\x12&\n\x0b\x61ntagonists\x18\x05 \x03(\x0b\x32\x11.proto.Antagonist\x12\x1a\n\x05items\x18\x06 \x03(\x0b\x32\x0b.proto.Item\x12\x1a\n\x05\x63oins\x18\x07 \x03(\x0b\x32\x0b.proto.Coin\"\x18\n\x06\x41\x63tion\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\x05\x32<\n\x0bGameService\x12-\n\tGetAction\x12\x0f.proto.GameData\x1a\r.proto.Action\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MARIO_STATEENTRY']._loaded_options = None
  _globals['_MARIO_STATEENTRY']._serialized_options = b'8\001'
  _globals['_POSITION']._serialized_start=21
  _globals['_POSITION']._serialized_end=53
  _globals['_DIMENSIONS']._serialized_start=55
  _globals['_DIMENSIONS']._serialized_end=98
  _globals['_MARIO']._serialized_start=101
  _globals['_MARIO']._serialized_end=290
  _globals['_MARIO_STATEENTRY']._serialized_start=246
  _globals['_MARIO_STATEENTRY']._serialized_end=290
  _globals['_ANTAGONIST']._serialized_start=293
  _globals['_ANTAGONIST']._serialized_end=442
  _globals['_ITEM']._serialized_start=444
  _globals['_ITEM']._serialized_end=538
  _globals['_COIN']._serialized_start=540
  _globals['_COIN']._serialized_end=620
  _globals['_GAMEDATA']._serialized_start=623
  _globals['_GAMEDATA']._serialized_end=841
  _globals['_ACTION']._serialized_start=843
  _globals['_ACTION']._serialized_end=867
  _globals['_GAMESERVICE']._serialized_start=869
  _globals['_GAMESERVICE']._serialized_end=929
# @@protoc_insertion_point(module_scope)
