// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

package proto;

public final class Data {
  private Data() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GameObjectOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.GameObject)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 x = 1;</code>
     * @return The x.
     */
    int getX();

    /**
     * <code>int32 y = 2;</code>
     * @return The y.
     */
    int getY();

    /**
     * <code>int32 height = 3;</code>
     * @return The height.
     */
    int getHeight();

    /**
     * <code>int32 width = 4;</code>
     * @return The width.
     */
    int getWidth();
  }
  /**
   * <pre>
   * Represents a game object with position and dimensions.
   * </pre>
   *
   * Protobuf type {@code proto.GameObject}
   */
  public static final class GameObject extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.GameObject)
      GameObjectOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GameObject.newBuilder() to construct.
    private GameObject(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GameObject() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GameObject();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.Data.internal_static_proto_GameObject_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.Data.internal_static_proto_GameObject_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.Data.GameObject.class, proto.Data.GameObject.Builder.class);
    }

    public static final int X_FIELD_NUMBER = 1;
    private int x_;
    /**
     * <code>int32 x = 1;</code>
     * @return The x.
     */
    @java.lang.Override
    public int getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private int y_;
    /**
     * <code>int32 y = 2;</code>
     * @return The y.
     */
    @java.lang.Override
    public int getY() {
      return y_;
    }

    public static final int HEIGHT_FIELD_NUMBER = 3;
    private int height_;
    /**
     * <code>int32 height = 3;</code>
     * @return The height.
     */
    @java.lang.Override
    public int getHeight() {
      return height_;
    }

    public static final int WIDTH_FIELD_NUMBER = 4;
    private int width_;
    /**
     * <code>int32 width = 4;</code>
     * @return The width.
     */
    @java.lang.Override
    public int getWidth() {
      return width_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (x_ != 0) {
        output.writeInt32(1, x_);
      }
      if (y_ != 0) {
        output.writeInt32(2, y_);
      }
      if (height_ != 0) {
        output.writeInt32(3, height_);
      }
      if (width_ != 0) {
        output.writeInt32(4, width_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (x_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, x_);
      }
      if (y_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, y_);
      }
      if (height_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, height_);
      }
      if (width_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, width_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.Data.GameObject)) {
        return super.equals(obj);
      }
      proto.Data.GameObject other = (proto.Data.GameObject) obj;

      if (getX()
          != other.getX()) return false;
      if (getY()
          != other.getY()) return false;
      if (getHeight()
          != other.getHeight()) return false;
      if (getWidth()
          != other.getWidth()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + getX();
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + getY();
      hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + getHeight();
      hash = (37 * hash) + WIDTH_FIELD_NUMBER;
      hash = (53 * hash) + getWidth();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.Data.GameObject parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Data.GameObject parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Data.GameObject parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Data.GameObject parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Data.GameObject parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Data.GameObject parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Data.GameObject parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.Data.GameObject parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.Data.GameObject parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.Data.GameObject parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.Data.GameObject parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.Data.GameObject parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.Data.GameObject prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Represents a game object with position and dimensions.
     * </pre>
     *
     * Protobuf type {@code proto.GameObject}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.GameObject)
        proto.Data.GameObjectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.Data.internal_static_proto_GameObject_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.Data.internal_static_proto_GameObject_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.Data.GameObject.class, proto.Data.GameObject.Builder.class);
      }

      // Construct using proto.Data.GameObject.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        x_ = 0;

        y_ = 0;

        height_ = 0;

        width_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.Data.internal_static_proto_GameObject_descriptor;
      }

      @java.lang.Override
      public proto.Data.GameObject getDefaultInstanceForType() {
        return proto.Data.GameObject.getDefaultInstance();
      }

      @java.lang.Override
      public proto.Data.GameObject build() {
        proto.Data.GameObject result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.Data.GameObject buildPartial() {
        proto.Data.GameObject result = new proto.Data.GameObject(this);
        result.x_ = x_;
        result.y_ = y_;
        result.height_ = height_;
        result.width_ = width_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.Data.GameObject) {
          return mergeFrom((proto.Data.GameObject)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.Data.GameObject other) {
        if (other == proto.Data.GameObject.getDefaultInstance()) return this;
        if (other.getX() != 0) {
          setX(other.getX());
        }
        if (other.getY() != 0) {
          setY(other.getY());
        }
        if (other.getHeight() != 0) {
          setHeight(other.getHeight());
        }
        if (other.getWidth() != 0) {
          setWidth(other.getWidth());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                x_ = input.readInt32();

                break;
              } // case 8
              case 16: {
                y_ = input.readInt32();

                break;
              } // case 16
              case 24: {
                height_ = input.readInt32();

                break;
              } // case 24
              case 32: {
                width_ = input.readInt32();

                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private int x_ ;
      /**
       * <code>int32 x = 1;</code>
       * @return The x.
       */
      @java.lang.Override
      public int getX() {
        return x_;
      }
      /**
       * <code>int32 x = 1;</code>
       * @param value The x to set.
       * @return This builder for chaining.
       */
      public Builder setX(int value) {
        
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 x = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearX() {
        
        x_ = 0;
        onChanged();
        return this;
      }

      private int y_ ;
      /**
       * <code>int32 y = 2;</code>
       * @return The y.
       */
      @java.lang.Override
      public int getY() {
        return y_;
      }
      /**
       * <code>int32 y = 2;</code>
       * @param value The y to set.
       * @return This builder for chaining.
       */
      public Builder setY(int value) {
        
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 y = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearY() {
        
        y_ = 0;
        onChanged();
        return this;
      }

      private int height_ ;
      /**
       * <code>int32 height = 3;</code>
       * @return The height.
       */
      @java.lang.Override
      public int getHeight() {
        return height_;
      }
      /**
       * <code>int32 height = 3;</code>
       * @param value The height to set.
       * @return This builder for chaining.
       */
      public Builder setHeight(int value) {
        
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 height = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeight() {
        
        height_ = 0;
        onChanged();
        return this;
      }

      private int width_ ;
      /**
       * <code>int32 width = 4;</code>
       * @return The width.
       */
      @java.lang.Override
      public int getWidth() {
        return width_;
      }
      /**
       * <code>int32 width = 4;</code>
       * @param value The width to set.
       * @return This builder for chaining.
       */
      public Builder setWidth(int value) {
        
        width_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 width = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearWidth() {
        
        width_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.GameObject)
    }

    // @@protoc_insertion_point(class_scope:proto.GameObject)
    private static final proto.Data.GameObject DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.Data.GameObject();
    }

    public static proto.Data.GameObject getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GameObject>
        PARSER = new com.google.protobuf.AbstractParser<GameObject>() {
      @java.lang.Override
      public GameObject parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GameObject> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GameObject> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.Data.GameObject getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GameDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.GameData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.proto.GameObject mario = 1;</code>
     * @return Whether the mario field is set.
     */
    boolean hasMario();
    /**
     * <code>.proto.GameObject mario = 1;</code>
     * @return The mario.
     */
    proto.Data.GameObject getMario();
    /**
     * <code>.proto.GameObject mario = 1;</code>
     */
    proto.Data.GameObjectOrBuilder getMarioOrBuilder();

    /**
     * <code>.proto.GameObject left_antagonist = 2;</code>
     * @return Whether the leftAntagonist field is set.
     */
    boolean hasLeftAntagonist();
    /**
     * <code>.proto.GameObject left_antagonist = 2;</code>
     * @return The leftAntagonist.
     */
    proto.Data.GameObject getLeftAntagonist();
    /**
     * <code>.proto.GameObject left_antagonist = 2;</code>
     */
    proto.Data.GameObjectOrBuilder getLeftAntagonistOrBuilder();

    /**
     * <code>.proto.GameObject right_antagonist = 3;</code>
     * @return Whether the rightAntagonist field is set.
     */
    boolean hasRightAntagonist();
    /**
     * <code>.proto.GameObject right_antagonist = 3;</code>
     * @return The rightAntagonist.
     */
    proto.Data.GameObject getRightAntagonist();
    /**
     * <code>.proto.GameObject right_antagonist = 3;</code>
     */
    proto.Data.GameObjectOrBuilder getRightAntagonistOrBuilder();

    /**
     * <code>int32 floor_level = 4;</code>
     * @return The floorLevel.
     */
    int getFloorLevel();

    /**
     * <code>.proto.GameObject left_object = 5;</code>
     * @return Whether the leftObject field is set.
     */
    boolean hasLeftObject();
    /**
     * <code>.proto.GameObject left_object = 5;</code>
     * @return The leftObject.
     */
    proto.Data.GameObject getLeftObject();
    /**
     * <code>.proto.GameObject left_object = 5;</code>
     */
    proto.Data.GameObjectOrBuilder getLeftObjectOrBuilder();

    /**
     * <code>.proto.GameObject right_object = 6;</code>
     * @return Whether the rightObject field is set.
     */
    boolean hasRightObject();
    /**
     * <code>.proto.GameObject right_object = 6;</code>
     * @return The rightObject.
     */
    proto.Data.GameObject getRightObject();
    /**
     * <code>.proto.GameObject right_object = 6;</code>
     */
    proto.Data.GameObjectOrBuilder getRightObjectOrBuilder();
  }
  /**
   * <pre>
   * Request data containing the state of the game.
   * </pre>
   *
   * Protobuf type {@code proto.GameData}
   */
  public static final class GameData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.GameData)
      GameDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GameData.newBuilder() to construct.
    private GameData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GameData() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GameData();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.Data.internal_static_proto_GameData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.Data.internal_static_proto_GameData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.Data.GameData.class, proto.Data.GameData.Builder.class);
    }

    public static final int MARIO_FIELD_NUMBER = 1;
    private proto.Data.GameObject mario_;
    /**
     * <code>.proto.GameObject mario = 1;</code>
     * @return Whether the mario field is set.
     */
    @java.lang.Override
    public boolean hasMario() {
      return mario_ != null;
    }
    /**
     * <code>.proto.GameObject mario = 1;</code>
     * @return The mario.
     */
    @java.lang.Override
    public proto.Data.GameObject getMario() {
      return mario_ == null ? proto.Data.GameObject.getDefaultInstance() : mario_;
    }
    /**
     * <code>.proto.GameObject mario = 1;</code>
     */
    @java.lang.Override
    public proto.Data.GameObjectOrBuilder getMarioOrBuilder() {
      return getMario();
    }

    public static final int LEFT_ANTAGONIST_FIELD_NUMBER = 2;
    private proto.Data.GameObject leftAntagonist_;
    /**
     * <code>.proto.GameObject left_antagonist = 2;</code>
     * @return Whether the leftAntagonist field is set.
     */
    @java.lang.Override
    public boolean hasLeftAntagonist() {
      return leftAntagonist_ != null;
    }
    /**
     * <code>.proto.GameObject left_antagonist = 2;</code>
     * @return The leftAntagonist.
     */
    @java.lang.Override
    public proto.Data.GameObject getLeftAntagonist() {
      return leftAntagonist_ == null ? proto.Data.GameObject.getDefaultInstance() : leftAntagonist_;
    }
    /**
     * <code>.proto.GameObject left_antagonist = 2;</code>
     */
    @java.lang.Override
    public proto.Data.GameObjectOrBuilder getLeftAntagonistOrBuilder() {
      return getLeftAntagonist();
    }

    public static final int RIGHT_ANTAGONIST_FIELD_NUMBER = 3;
    private proto.Data.GameObject rightAntagonist_;
    /**
     * <code>.proto.GameObject right_antagonist = 3;</code>
     * @return Whether the rightAntagonist field is set.
     */
    @java.lang.Override
    public boolean hasRightAntagonist() {
      return rightAntagonist_ != null;
    }
    /**
     * <code>.proto.GameObject right_antagonist = 3;</code>
     * @return The rightAntagonist.
     */
    @java.lang.Override
    public proto.Data.GameObject getRightAntagonist() {
      return rightAntagonist_ == null ? proto.Data.GameObject.getDefaultInstance() : rightAntagonist_;
    }
    /**
     * <code>.proto.GameObject right_antagonist = 3;</code>
     */
    @java.lang.Override
    public proto.Data.GameObjectOrBuilder getRightAntagonistOrBuilder() {
      return getRightAntagonist();
    }

    public static final int FLOOR_LEVEL_FIELD_NUMBER = 4;
    private int floorLevel_;
    /**
     * <code>int32 floor_level = 4;</code>
     * @return The floorLevel.
     */
    @java.lang.Override
    public int getFloorLevel() {
      return floorLevel_;
    }

    public static final int LEFT_OBJECT_FIELD_NUMBER = 5;
    private proto.Data.GameObject leftObject_;
    /**
     * <code>.proto.GameObject left_object = 5;</code>
     * @return Whether the leftObject field is set.
     */
    @java.lang.Override
    public boolean hasLeftObject() {
      return leftObject_ != null;
    }
    /**
     * <code>.proto.GameObject left_object = 5;</code>
     * @return The leftObject.
     */
    @java.lang.Override
    public proto.Data.GameObject getLeftObject() {
      return leftObject_ == null ? proto.Data.GameObject.getDefaultInstance() : leftObject_;
    }
    /**
     * <code>.proto.GameObject left_object = 5;</code>
     */
    @java.lang.Override
    public proto.Data.GameObjectOrBuilder getLeftObjectOrBuilder() {
      return getLeftObject();
    }

    public static final int RIGHT_OBJECT_FIELD_NUMBER = 6;
    private proto.Data.GameObject rightObject_;
    /**
     * <code>.proto.GameObject right_object = 6;</code>
     * @return Whether the rightObject field is set.
     */
    @java.lang.Override
    public boolean hasRightObject() {
      return rightObject_ != null;
    }
    /**
     * <code>.proto.GameObject right_object = 6;</code>
     * @return The rightObject.
     */
    @java.lang.Override
    public proto.Data.GameObject getRightObject() {
      return rightObject_ == null ? proto.Data.GameObject.getDefaultInstance() : rightObject_;
    }
    /**
     * <code>.proto.GameObject right_object = 6;</code>
     */
    @java.lang.Override
    public proto.Data.GameObjectOrBuilder getRightObjectOrBuilder() {
      return getRightObject();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (mario_ != null) {
        output.writeMessage(1, getMario());
      }
      if (leftAntagonist_ != null) {
        output.writeMessage(2, getLeftAntagonist());
      }
      if (rightAntagonist_ != null) {
        output.writeMessage(3, getRightAntagonist());
      }
      if (floorLevel_ != 0) {
        output.writeInt32(4, floorLevel_);
      }
      if (leftObject_ != null) {
        output.writeMessage(5, getLeftObject());
      }
      if (rightObject_ != null) {
        output.writeMessage(6, getRightObject());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (mario_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMario());
      }
      if (leftAntagonist_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getLeftAntagonist());
      }
      if (rightAntagonist_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getRightAntagonist());
      }
      if (floorLevel_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, floorLevel_);
      }
      if (leftObject_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getLeftObject());
      }
      if (rightObject_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getRightObject());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.Data.GameData)) {
        return super.equals(obj);
      }
      proto.Data.GameData other = (proto.Data.GameData) obj;

      if (hasMario() != other.hasMario()) return false;
      if (hasMario()) {
        if (!getMario()
            .equals(other.getMario())) return false;
      }
      if (hasLeftAntagonist() != other.hasLeftAntagonist()) return false;
      if (hasLeftAntagonist()) {
        if (!getLeftAntagonist()
            .equals(other.getLeftAntagonist())) return false;
      }
      if (hasRightAntagonist() != other.hasRightAntagonist()) return false;
      if (hasRightAntagonist()) {
        if (!getRightAntagonist()
            .equals(other.getRightAntagonist())) return false;
      }
      if (getFloorLevel()
          != other.getFloorLevel()) return false;
      if (hasLeftObject() != other.hasLeftObject()) return false;
      if (hasLeftObject()) {
        if (!getLeftObject()
            .equals(other.getLeftObject())) return false;
      }
      if (hasRightObject() != other.hasRightObject()) return false;
      if (hasRightObject()) {
        if (!getRightObject()
            .equals(other.getRightObject())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMario()) {
        hash = (37 * hash) + MARIO_FIELD_NUMBER;
        hash = (53 * hash) + getMario().hashCode();
      }
      if (hasLeftAntagonist()) {
        hash = (37 * hash) + LEFT_ANTAGONIST_FIELD_NUMBER;
        hash = (53 * hash) + getLeftAntagonist().hashCode();
      }
      if (hasRightAntagonist()) {
        hash = (37 * hash) + RIGHT_ANTAGONIST_FIELD_NUMBER;
        hash = (53 * hash) + getRightAntagonist().hashCode();
      }
      hash = (37 * hash) + FLOOR_LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getFloorLevel();
      if (hasLeftObject()) {
        hash = (37 * hash) + LEFT_OBJECT_FIELD_NUMBER;
        hash = (53 * hash) + getLeftObject().hashCode();
      }
      if (hasRightObject()) {
        hash = (37 * hash) + RIGHT_OBJECT_FIELD_NUMBER;
        hash = (53 * hash) + getRightObject().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.Data.GameData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Data.GameData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Data.GameData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Data.GameData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Data.GameData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Data.GameData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Data.GameData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.Data.GameData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.Data.GameData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.Data.GameData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.Data.GameData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.Data.GameData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.Data.GameData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Request data containing the state of the game.
     * </pre>
     *
     * Protobuf type {@code proto.GameData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.GameData)
        proto.Data.GameDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.Data.internal_static_proto_GameData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.Data.internal_static_proto_GameData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.Data.GameData.class, proto.Data.GameData.Builder.class);
      }

      // Construct using proto.Data.GameData.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (marioBuilder_ == null) {
          mario_ = null;
        } else {
          mario_ = null;
          marioBuilder_ = null;
        }
        if (leftAntagonistBuilder_ == null) {
          leftAntagonist_ = null;
        } else {
          leftAntagonist_ = null;
          leftAntagonistBuilder_ = null;
        }
        if (rightAntagonistBuilder_ == null) {
          rightAntagonist_ = null;
        } else {
          rightAntagonist_ = null;
          rightAntagonistBuilder_ = null;
        }
        floorLevel_ = 0;

        if (leftObjectBuilder_ == null) {
          leftObject_ = null;
        } else {
          leftObject_ = null;
          leftObjectBuilder_ = null;
        }
        if (rightObjectBuilder_ == null) {
          rightObject_ = null;
        } else {
          rightObject_ = null;
          rightObjectBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.Data.internal_static_proto_GameData_descriptor;
      }

      @java.lang.Override
      public proto.Data.GameData getDefaultInstanceForType() {
        return proto.Data.GameData.getDefaultInstance();
      }

      @java.lang.Override
      public proto.Data.GameData build() {
        proto.Data.GameData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.Data.GameData buildPartial() {
        proto.Data.GameData result = new proto.Data.GameData(this);
        if (marioBuilder_ == null) {
          result.mario_ = mario_;
        } else {
          result.mario_ = marioBuilder_.build();
        }
        if (leftAntagonistBuilder_ == null) {
          result.leftAntagonist_ = leftAntagonist_;
        } else {
          result.leftAntagonist_ = leftAntagonistBuilder_.build();
        }
        if (rightAntagonistBuilder_ == null) {
          result.rightAntagonist_ = rightAntagonist_;
        } else {
          result.rightAntagonist_ = rightAntagonistBuilder_.build();
        }
        result.floorLevel_ = floorLevel_;
        if (leftObjectBuilder_ == null) {
          result.leftObject_ = leftObject_;
        } else {
          result.leftObject_ = leftObjectBuilder_.build();
        }
        if (rightObjectBuilder_ == null) {
          result.rightObject_ = rightObject_;
        } else {
          result.rightObject_ = rightObjectBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.Data.GameData) {
          return mergeFrom((proto.Data.GameData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.Data.GameData other) {
        if (other == proto.Data.GameData.getDefaultInstance()) return this;
        if (other.hasMario()) {
          mergeMario(other.getMario());
        }
        if (other.hasLeftAntagonist()) {
          mergeLeftAntagonist(other.getLeftAntagonist());
        }
        if (other.hasRightAntagonist()) {
          mergeRightAntagonist(other.getRightAntagonist());
        }
        if (other.getFloorLevel() != 0) {
          setFloorLevel(other.getFloorLevel());
        }
        if (other.hasLeftObject()) {
          mergeLeftObject(other.getLeftObject());
        }
        if (other.hasRightObject()) {
          mergeRightObject(other.getRightObject());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getMarioFieldBuilder().getBuilder(),
                    extensionRegistry);

                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getLeftAntagonistFieldBuilder().getBuilder(),
                    extensionRegistry);

                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getRightAntagonistFieldBuilder().getBuilder(),
                    extensionRegistry);

                break;
              } // case 26
              case 32: {
                floorLevel_ = input.readInt32();

                break;
              } // case 32
              case 42: {
                input.readMessage(
                    getLeftObjectFieldBuilder().getBuilder(),
                    extensionRegistry);

                break;
              } // case 42
              case 50: {
                input.readMessage(
                    getRightObjectFieldBuilder().getBuilder(),
                    extensionRegistry);

                break;
              } // case 50
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private proto.Data.GameObject mario_;
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.Data.GameObject, proto.Data.GameObject.Builder, proto.Data.GameObjectOrBuilder> marioBuilder_;
      /**
       * <code>.proto.GameObject mario = 1;</code>
       * @return Whether the mario field is set.
       */
      public boolean hasMario() {
        return marioBuilder_ != null || mario_ != null;
      }
      /**
       * <code>.proto.GameObject mario = 1;</code>
       * @return The mario.
       */
      public proto.Data.GameObject getMario() {
        if (marioBuilder_ == null) {
          return mario_ == null ? proto.Data.GameObject.getDefaultInstance() : mario_;
        } else {
          return marioBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto.GameObject mario = 1;</code>
       */
      public Builder setMario(proto.Data.GameObject value) {
        if (marioBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          mario_ = value;
          onChanged();
        } else {
          marioBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.proto.GameObject mario = 1;</code>
       */
      public Builder setMario(
          proto.Data.GameObject.Builder builderForValue) {
        if (marioBuilder_ == null) {
          mario_ = builderForValue.build();
          onChanged();
        } else {
          marioBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.proto.GameObject mario = 1;</code>
       */
      public Builder mergeMario(proto.Data.GameObject value) {
        if (marioBuilder_ == null) {
          if (mario_ != null) {
            mario_ =
              proto.Data.GameObject.newBuilder(mario_).mergeFrom(value).buildPartial();
          } else {
            mario_ = value;
          }
          onChanged();
        } else {
          marioBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.proto.GameObject mario = 1;</code>
       */
      public Builder clearMario() {
        if (marioBuilder_ == null) {
          mario_ = null;
          onChanged();
        } else {
          mario_ = null;
          marioBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.proto.GameObject mario = 1;</code>
       */
      public proto.Data.GameObject.Builder getMarioBuilder() {
        
        onChanged();
        return getMarioFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.GameObject mario = 1;</code>
       */
      public proto.Data.GameObjectOrBuilder getMarioOrBuilder() {
        if (marioBuilder_ != null) {
          return marioBuilder_.getMessageOrBuilder();
        } else {
          return mario_ == null ?
              proto.Data.GameObject.getDefaultInstance() : mario_;
        }
      }
      /**
       * <code>.proto.GameObject mario = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.Data.GameObject, proto.Data.GameObject.Builder, proto.Data.GameObjectOrBuilder> 
          getMarioFieldBuilder() {
        if (marioBuilder_ == null) {
          marioBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto.Data.GameObject, proto.Data.GameObject.Builder, proto.Data.GameObjectOrBuilder>(
                  getMario(),
                  getParentForChildren(),
                  isClean());
          mario_ = null;
        }
        return marioBuilder_;
      }

      private proto.Data.GameObject leftAntagonist_;
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.Data.GameObject, proto.Data.GameObject.Builder, proto.Data.GameObjectOrBuilder> leftAntagonistBuilder_;
      /**
       * <code>.proto.GameObject left_antagonist = 2;</code>
       * @return Whether the leftAntagonist field is set.
       */
      public boolean hasLeftAntagonist() {
        return leftAntagonistBuilder_ != null || leftAntagonist_ != null;
      }
      /**
       * <code>.proto.GameObject left_antagonist = 2;</code>
       * @return The leftAntagonist.
       */
      public proto.Data.GameObject getLeftAntagonist() {
        if (leftAntagonistBuilder_ == null) {
          return leftAntagonist_ == null ? proto.Data.GameObject.getDefaultInstance() : leftAntagonist_;
        } else {
          return leftAntagonistBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto.GameObject left_antagonist = 2;</code>
       */
      public Builder setLeftAntagonist(proto.Data.GameObject value) {
        if (leftAntagonistBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          leftAntagonist_ = value;
          onChanged();
        } else {
          leftAntagonistBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.proto.GameObject left_antagonist = 2;</code>
       */
      public Builder setLeftAntagonist(
          proto.Data.GameObject.Builder builderForValue) {
        if (leftAntagonistBuilder_ == null) {
          leftAntagonist_ = builderForValue.build();
          onChanged();
        } else {
          leftAntagonistBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.proto.GameObject left_antagonist = 2;</code>
       */
      public Builder mergeLeftAntagonist(proto.Data.GameObject value) {
        if (leftAntagonistBuilder_ == null) {
          if (leftAntagonist_ != null) {
            leftAntagonist_ =
              proto.Data.GameObject.newBuilder(leftAntagonist_).mergeFrom(value).buildPartial();
          } else {
            leftAntagonist_ = value;
          }
          onChanged();
        } else {
          leftAntagonistBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.proto.GameObject left_antagonist = 2;</code>
       */
      public Builder clearLeftAntagonist() {
        if (leftAntagonistBuilder_ == null) {
          leftAntagonist_ = null;
          onChanged();
        } else {
          leftAntagonist_ = null;
          leftAntagonistBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.proto.GameObject left_antagonist = 2;</code>
       */
      public proto.Data.GameObject.Builder getLeftAntagonistBuilder() {
        
        onChanged();
        return getLeftAntagonistFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.GameObject left_antagonist = 2;</code>
       */
      public proto.Data.GameObjectOrBuilder getLeftAntagonistOrBuilder() {
        if (leftAntagonistBuilder_ != null) {
          return leftAntagonistBuilder_.getMessageOrBuilder();
        } else {
          return leftAntagonist_ == null ?
              proto.Data.GameObject.getDefaultInstance() : leftAntagonist_;
        }
      }
      /**
       * <code>.proto.GameObject left_antagonist = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.Data.GameObject, proto.Data.GameObject.Builder, proto.Data.GameObjectOrBuilder> 
          getLeftAntagonistFieldBuilder() {
        if (leftAntagonistBuilder_ == null) {
          leftAntagonistBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto.Data.GameObject, proto.Data.GameObject.Builder, proto.Data.GameObjectOrBuilder>(
                  getLeftAntagonist(),
                  getParentForChildren(),
                  isClean());
          leftAntagonist_ = null;
        }
        return leftAntagonistBuilder_;
      }

      private proto.Data.GameObject rightAntagonist_;
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.Data.GameObject, proto.Data.GameObject.Builder, proto.Data.GameObjectOrBuilder> rightAntagonistBuilder_;
      /**
       * <code>.proto.GameObject right_antagonist = 3;</code>
       * @return Whether the rightAntagonist field is set.
       */
      public boolean hasRightAntagonist() {
        return rightAntagonistBuilder_ != null || rightAntagonist_ != null;
      }
      /**
       * <code>.proto.GameObject right_antagonist = 3;</code>
       * @return The rightAntagonist.
       */
      public proto.Data.GameObject getRightAntagonist() {
        if (rightAntagonistBuilder_ == null) {
          return rightAntagonist_ == null ? proto.Data.GameObject.getDefaultInstance() : rightAntagonist_;
        } else {
          return rightAntagonistBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto.GameObject right_antagonist = 3;</code>
       */
      public Builder setRightAntagonist(proto.Data.GameObject value) {
        if (rightAntagonistBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          rightAntagonist_ = value;
          onChanged();
        } else {
          rightAntagonistBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.proto.GameObject right_antagonist = 3;</code>
       */
      public Builder setRightAntagonist(
          proto.Data.GameObject.Builder builderForValue) {
        if (rightAntagonistBuilder_ == null) {
          rightAntagonist_ = builderForValue.build();
          onChanged();
        } else {
          rightAntagonistBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.proto.GameObject right_antagonist = 3;</code>
       */
      public Builder mergeRightAntagonist(proto.Data.GameObject value) {
        if (rightAntagonistBuilder_ == null) {
          if (rightAntagonist_ != null) {
            rightAntagonist_ =
              proto.Data.GameObject.newBuilder(rightAntagonist_).mergeFrom(value).buildPartial();
          } else {
            rightAntagonist_ = value;
          }
          onChanged();
        } else {
          rightAntagonistBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.proto.GameObject right_antagonist = 3;</code>
       */
      public Builder clearRightAntagonist() {
        if (rightAntagonistBuilder_ == null) {
          rightAntagonist_ = null;
          onChanged();
        } else {
          rightAntagonist_ = null;
          rightAntagonistBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.proto.GameObject right_antagonist = 3;</code>
       */
      public proto.Data.GameObject.Builder getRightAntagonistBuilder() {
        
        onChanged();
        return getRightAntagonistFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.GameObject right_antagonist = 3;</code>
       */
      public proto.Data.GameObjectOrBuilder getRightAntagonistOrBuilder() {
        if (rightAntagonistBuilder_ != null) {
          return rightAntagonistBuilder_.getMessageOrBuilder();
        } else {
          return rightAntagonist_ == null ?
              proto.Data.GameObject.getDefaultInstance() : rightAntagonist_;
        }
      }
      /**
       * <code>.proto.GameObject right_antagonist = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.Data.GameObject, proto.Data.GameObject.Builder, proto.Data.GameObjectOrBuilder> 
          getRightAntagonistFieldBuilder() {
        if (rightAntagonistBuilder_ == null) {
          rightAntagonistBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto.Data.GameObject, proto.Data.GameObject.Builder, proto.Data.GameObjectOrBuilder>(
                  getRightAntagonist(),
                  getParentForChildren(),
                  isClean());
          rightAntagonist_ = null;
        }
        return rightAntagonistBuilder_;
      }

      private int floorLevel_ ;
      /**
       * <code>int32 floor_level = 4;</code>
       * @return The floorLevel.
       */
      @java.lang.Override
      public int getFloorLevel() {
        return floorLevel_;
      }
      /**
       * <code>int32 floor_level = 4;</code>
       * @param value The floorLevel to set.
       * @return This builder for chaining.
       */
      public Builder setFloorLevel(int value) {
        
        floorLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 floor_level = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFloorLevel() {
        
        floorLevel_ = 0;
        onChanged();
        return this;
      }

      private proto.Data.GameObject leftObject_;
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.Data.GameObject, proto.Data.GameObject.Builder, proto.Data.GameObjectOrBuilder> leftObjectBuilder_;
      /**
       * <code>.proto.GameObject left_object = 5;</code>
       * @return Whether the leftObject field is set.
       */
      public boolean hasLeftObject() {
        return leftObjectBuilder_ != null || leftObject_ != null;
      }
      /**
       * <code>.proto.GameObject left_object = 5;</code>
       * @return The leftObject.
       */
      public proto.Data.GameObject getLeftObject() {
        if (leftObjectBuilder_ == null) {
          return leftObject_ == null ? proto.Data.GameObject.getDefaultInstance() : leftObject_;
        } else {
          return leftObjectBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto.GameObject left_object = 5;</code>
       */
      public Builder setLeftObject(proto.Data.GameObject value) {
        if (leftObjectBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          leftObject_ = value;
          onChanged();
        } else {
          leftObjectBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.proto.GameObject left_object = 5;</code>
       */
      public Builder setLeftObject(
          proto.Data.GameObject.Builder builderForValue) {
        if (leftObjectBuilder_ == null) {
          leftObject_ = builderForValue.build();
          onChanged();
        } else {
          leftObjectBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.proto.GameObject left_object = 5;</code>
       */
      public Builder mergeLeftObject(proto.Data.GameObject value) {
        if (leftObjectBuilder_ == null) {
          if (leftObject_ != null) {
            leftObject_ =
              proto.Data.GameObject.newBuilder(leftObject_).mergeFrom(value).buildPartial();
          } else {
            leftObject_ = value;
          }
          onChanged();
        } else {
          leftObjectBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.proto.GameObject left_object = 5;</code>
       */
      public Builder clearLeftObject() {
        if (leftObjectBuilder_ == null) {
          leftObject_ = null;
          onChanged();
        } else {
          leftObject_ = null;
          leftObjectBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.proto.GameObject left_object = 5;</code>
       */
      public proto.Data.GameObject.Builder getLeftObjectBuilder() {
        
        onChanged();
        return getLeftObjectFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.GameObject left_object = 5;</code>
       */
      public proto.Data.GameObjectOrBuilder getLeftObjectOrBuilder() {
        if (leftObjectBuilder_ != null) {
          return leftObjectBuilder_.getMessageOrBuilder();
        } else {
          return leftObject_ == null ?
              proto.Data.GameObject.getDefaultInstance() : leftObject_;
        }
      }
      /**
       * <code>.proto.GameObject left_object = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.Data.GameObject, proto.Data.GameObject.Builder, proto.Data.GameObjectOrBuilder> 
          getLeftObjectFieldBuilder() {
        if (leftObjectBuilder_ == null) {
          leftObjectBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto.Data.GameObject, proto.Data.GameObject.Builder, proto.Data.GameObjectOrBuilder>(
                  getLeftObject(),
                  getParentForChildren(),
                  isClean());
          leftObject_ = null;
        }
        return leftObjectBuilder_;
      }

      private proto.Data.GameObject rightObject_;
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.Data.GameObject, proto.Data.GameObject.Builder, proto.Data.GameObjectOrBuilder> rightObjectBuilder_;
      /**
       * <code>.proto.GameObject right_object = 6;</code>
       * @return Whether the rightObject field is set.
       */
      public boolean hasRightObject() {
        return rightObjectBuilder_ != null || rightObject_ != null;
      }
      /**
       * <code>.proto.GameObject right_object = 6;</code>
       * @return The rightObject.
       */
      public proto.Data.GameObject getRightObject() {
        if (rightObjectBuilder_ == null) {
          return rightObject_ == null ? proto.Data.GameObject.getDefaultInstance() : rightObject_;
        } else {
          return rightObjectBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto.GameObject right_object = 6;</code>
       */
      public Builder setRightObject(proto.Data.GameObject value) {
        if (rightObjectBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          rightObject_ = value;
          onChanged();
        } else {
          rightObjectBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.proto.GameObject right_object = 6;</code>
       */
      public Builder setRightObject(
          proto.Data.GameObject.Builder builderForValue) {
        if (rightObjectBuilder_ == null) {
          rightObject_ = builderForValue.build();
          onChanged();
        } else {
          rightObjectBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.proto.GameObject right_object = 6;</code>
       */
      public Builder mergeRightObject(proto.Data.GameObject value) {
        if (rightObjectBuilder_ == null) {
          if (rightObject_ != null) {
            rightObject_ =
              proto.Data.GameObject.newBuilder(rightObject_).mergeFrom(value).buildPartial();
          } else {
            rightObject_ = value;
          }
          onChanged();
        } else {
          rightObjectBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.proto.GameObject right_object = 6;</code>
       */
      public Builder clearRightObject() {
        if (rightObjectBuilder_ == null) {
          rightObject_ = null;
          onChanged();
        } else {
          rightObject_ = null;
          rightObjectBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.proto.GameObject right_object = 6;</code>
       */
      public proto.Data.GameObject.Builder getRightObjectBuilder() {
        
        onChanged();
        return getRightObjectFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.GameObject right_object = 6;</code>
       */
      public proto.Data.GameObjectOrBuilder getRightObjectOrBuilder() {
        if (rightObjectBuilder_ != null) {
          return rightObjectBuilder_.getMessageOrBuilder();
        } else {
          return rightObject_ == null ?
              proto.Data.GameObject.getDefaultInstance() : rightObject_;
        }
      }
      /**
       * <code>.proto.GameObject right_object = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.Data.GameObject, proto.Data.GameObject.Builder, proto.Data.GameObjectOrBuilder> 
          getRightObjectFieldBuilder() {
        if (rightObjectBuilder_ == null) {
          rightObjectBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto.Data.GameObject, proto.Data.GameObject.Builder, proto.Data.GameObjectOrBuilder>(
                  getRightObject(),
                  getParentForChildren(),
                  isClean());
          rightObject_ = null;
        }
        return rightObjectBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.GameData)
    }

    // @@protoc_insertion_point(class_scope:proto.GameData)
    private static final proto.Data.GameData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.Data.GameData();
    }

    public static proto.Data.GameData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GameData>
        PARSER = new com.google.protobuf.AbstractParser<GameData>() {
      @java.lang.Override
      public GameData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GameData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GameData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.Data.GameData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ActionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Action)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 action = 1;</code>
     * @return The action.
     */
    int getAction();
  }
  /**
   * <pre>
   * Response data containing the action to be taken.
   * </pre>
   *
   * Protobuf type {@code proto.Action}
   */
  public static final class Action extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.Action)
      ActionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Action.newBuilder() to construct.
    private Action(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Action() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Action();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.Data.internal_static_proto_Action_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.Data.internal_static_proto_Action_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.Data.Action.class, proto.Data.Action.Builder.class);
    }

    public static final int ACTION_FIELD_NUMBER = 1;
    private int action_;
    /**
     * <code>int32 action = 1;</code>
     * @return The action.
     */
    @java.lang.Override
    public int getAction() {
      return action_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (action_ != 0) {
        output.writeInt32(1, action_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (action_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, action_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.Data.Action)) {
        return super.equals(obj);
      }
      proto.Data.Action other = (proto.Data.Action) obj;

      if (getAction()
          != other.getAction()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ACTION_FIELD_NUMBER;
      hash = (53 * hash) + getAction();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.Data.Action parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Data.Action parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Data.Action parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Data.Action parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Data.Action parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Data.Action parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Data.Action parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.Data.Action parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.Data.Action parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.Data.Action parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.Data.Action parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.Data.Action parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.Data.Action prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Response data containing the action to be taken.
     * </pre>
     *
     * Protobuf type {@code proto.Action}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Action)
        proto.Data.ActionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.Data.internal_static_proto_Action_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.Data.internal_static_proto_Action_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.Data.Action.class, proto.Data.Action.Builder.class);
      }

      // Construct using proto.Data.Action.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        action_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.Data.internal_static_proto_Action_descriptor;
      }

      @java.lang.Override
      public proto.Data.Action getDefaultInstanceForType() {
        return proto.Data.Action.getDefaultInstance();
      }

      @java.lang.Override
      public proto.Data.Action build() {
        proto.Data.Action result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.Data.Action buildPartial() {
        proto.Data.Action result = new proto.Data.Action(this);
        result.action_ = action_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.Data.Action) {
          return mergeFrom((proto.Data.Action)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.Data.Action other) {
        if (other == proto.Data.Action.getDefaultInstance()) return this;
        if (other.getAction() != 0) {
          setAction(other.getAction());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                action_ = input.readInt32();

                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private int action_ ;
      /**
       * <code>int32 action = 1;</code>
       * @return The action.
       */
      @java.lang.Override
      public int getAction() {
        return action_;
      }
      /**
       * <code>int32 action = 1;</code>
       * @param value The action to set.
       * @return This builder for chaining.
       */
      public Builder setAction(int value) {
        
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 action = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAction() {
        
        action_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.Action)
    }

    // @@protoc_insertion_point(class_scope:proto.Action)
    private static final proto.Data.Action DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.Data.Action();
    }

    public static proto.Data.Action getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Action>
        PARSER = new com.google.protobuf.AbstractParser<Action>() {
      @java.lang.Override
      public Action parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Action> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Action> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.Data.Action getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_GameObject_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_GameObject_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_GameData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_GameData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Action_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Action_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ndata.proto\022\005proto\"A\n\nGameObject\022\t\n\001x\030\001" +
      " \001(\005\022\t\n\001y\030\002 \001(\005\022\016\n\006height\030\003 \001(\005\022\r\n\005width" +
      "\030\004 \001(\005\"\353\001\n\010GameData\022 \n\005mario\030\001 \001(\0132\021.pro" +
      "to.GameObject\022*\n\017left_antagonist\030\002 \001(\0132\021" +
      ".proto.GameObject\022+\n\020right_antagonist\030\003 " +
      "\001(\0132\021.proto.GameObject\022\023\n\013floor_level\030\004 " +
      "\001(\005\022&\n\013left_object\030\005 \001(\0132\021.proto.GameObj" +
      "ect\022\'\n\014right_object\030\006 \001(\0132\021.proto.GameOb" +
      "ject\"\030\n\006Action\022\016\n\006action\030\001 \001(\0052<\n\013GameSe" +
      "rvice\022-\n\tGetAction\022\017.proto.GameData\032\r.pr" +
      "oto.Action\"\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_GameObject_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_GameObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_GameObject_descriptor,
        new java.lang.String[] { "X", "Y", "Height", "Width", });
    internal_static_proto_GameData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_GameData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_GameData_descriptor,
        new java.lang.String[] { "Mario", "LeftAntagonist", "RightAntagonist", "FloorLevel", "LeftObject", "RightObject", });
    internal_static_proto_Action_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_Action_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Action_descriptor,
        new java.lang.String[] { "Action", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
